Repository OTService/forgottenserver, pull requests merged in 2022-09, with the labels that each got.

#1 luascript.cpp/h rework
  .github/workflows/build-vcpkg.yml
  src/CMakeLists.txt
  src/actions.cpp
  src/chat.cpp
  src/combat.cpp
  src/configmanager.cpp
  src/creature.h
  src/creatureevent.cpp
  src/databasemanager.cpp
  src/events.cpp
  src/item.h
  src/luaaction.cpp
  src/luacombat.cpp
  src/luacondition.cpp
  src/luacontainer.cpp
  src/luacreature.cpp
  src/luacreatureevent.cpp
  src/luaenums.cpp
  src/luagame.cpp
  src/luaglobalevent.cpp
  src/luagroup.cpp
  src/luaguild.cpp
  src/luahouse.cpp
  src/luaitem.cpp
  src/luaitemtype.cpp
  src/lualoot.cpp
  src/luamodalwindow.cpp
  src/luamonster.cpp
  src/luamonsterspell.cpp
  src/luamonstertype.cpp
  src/luamoveevent.cpp
  src/luanetworkmessage.cpp
  src/luanpc.cpp
  src/luaparty.cpp
  src/luaplayer.cpp
  src/luaposition.cpp
  src/luascript.cpp
  src/luascript.h
  src/luaspell.cpp
  src/luatalkaction.cpp
  src/luatile.cpp
  src/luatown.cpp
  src/luavocation.cpp
  src/luaweapon.cpp
  src/luaxml.cpp
  src/monster.cpp
  src/monster.h
  src/movement.cpp
  src/npc.cpp
  src/player.h
  src/spells.cpp
  src/talkaction.cpp
  src/weapons.cpp
  vc17/theforgottenserver.vcxproj
  vc17/theforgottenserver.vcxproj.filters
Labels: enhancement

#5 Outfit(addons) & Mounts database changes
  data/migrations/34.lua
  data/migrations/35.lua
  schema.sql
  src/const.h
  src/creature.h
  src/iologindata.cpp
  src/mounts.cpp
  src/mounts.h
  src/player.cpp
  src/player.h
Labels: enhancement, bugfix

#8 [revscriptsys] adding ItemType properties
  data/items/items.lua
  data/lib/core/item.lua
  data/scripts/lib/register_item_type.lua
  src/luaitemtype.cpp
Labels: enhancement, revscriptsys

#9 Items.xml & Items.otb removal
  data/items/items.lua
  data/items/items.otb
  data/items/items.xml
  data/scripts/lib/register_item_type.lua
  src/definitions.h
  src/iomap.cpp
  src/items.cpp
  src/items.h
  src/luagame.cpp
  src/luaitemtype.cpp
  src/luascript.cpp
  src/luascript.h
  src/otserv.cpp
  src/scriptmanager.cpp
Labels: enhancement, revscriptsys

#11 Fix depots
  src/luaitemtype.cpp
Labels: bugfix

#12 Item loading re work
  .github/workflows/build-vcpkg.yml
  data/scripts/talkactions/reload.lua
  data/talkactions/talkactions.xml
  src/const.h
  src/game.cpp
  src/items.cpp
  src/items.h
  src/luaenums.cpp
  src/luagame.cpp
  src/luaitemtype.cpp
  src/otserv.cpp
  src/script.cpp
  src/script.h
  src/scriptmanager.cpp
  src/signals.cpp
Labels: enhancement, revscriptsys

#15 ItemType fix pushnil problem
  data/talkactions/scripts/create_item.lua
  src/luaitemtype.cpp
Labels: bugfix

#13 Library folder merging & rework on the loading functions
  data/lib/000global.lua
  data/lib/001core/000storages.lua
  data/lib/001core/achievements.lua
  data/lib/001core/actionids.lua
  data/lib/001core/combat.lua
  data/lib/001core/constants.lua
  data/lib/001core/container.lua
  data/lib/001core/creature.lua
  data/lib/001core/game.lua
  data/lib/001core/item.lua
  data/lib/001core/itemtype.lua
  data/lib/001core/party.lua
  data/lib/001core/player.lua
  data/lib/001core/podium.lua
  data/lib/001core/position.lua
  data/lib/001core/teleport.lua
  data/lib/001core/tile.lua
  data/lib/001core/vocation.lua
  data/lib/002compat/compat.lua
  data/lib/003debugging/dump.lua
  data/lib/003debugging/xml.lua
  data/lib/004register/event_callbacks.lua
  data/lib/004register/register_item_type.lua
  data/lib/004register/register_monster_type.lua
  data/lib/005misc/create_functions.lua
  data/lib/005misc/defaults_move_event.lua
  data/lib/005misc/helper_constructors.lua
  data/lib/core/core.lua
  data/lib/debugging/lua_version.lua
  data/lib/lib.lua
  data/scripts/talkactions/reload.lua
  src/const.h
  src/game.cpp
  src/luaenums.cpp
  src/luagame.cpp
  src/otserv.cpp
  src/script.cpp
  src/script.h
  src/scriptmanager.cpp
Labels: enhancement, revscriptsys
